//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACADEMIC_LEVEL
    {
        public ACADEMIC_LEVEL()
        {
            this.RECRUITMENTs = new HashSet<RECRUITMENT>();
        }
    
        public int AcademicLevelId { get; set; }
        public string AcademicLevelName { get; set; }
        public int CompanyId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual ICollection<RECRUITMENT> RECRUITMENTs { get; set; }
    }
}
