//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_ERROR_LOG
    {
        public int ErrorLogId { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime Created_Date { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
