//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION_CONFIGURATION
    {
        public int ApplicationConfigurationId { get; set; }
        public string ApplicationConfigurationName { get; set; }
        public string ApplicationConfigurationValue { get; set; }
        public bool IsActive { get; set; }
    }
}
