//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITY
    {
        public CITY()
        {
            this.AREAs = new HashSet<AREA>();
            this.COMPANies = new HashSet<COMPANY>();
            this.PIN_CODE = new HashSet<PIN_CODE>();
            this.USERs = new HashSet<USER>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public int StateId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<AREA> AREAs { get; set; }
        public virtual STATE STATE { get; set; }
        public virtual ICollection<COMPANY> COMPANies { get; set; }
        public virtual ICollection<PIN_CODE> PIN_CODE { get; set; }
        public virtual ICollection<USER> USERs { get; set; }
    }
}
