//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public COMPANY()
        {
            this.ACADEMIC_LEVEL = new HashSet<ACADEMIC_LEVEL>();
            this.BANNERs = new HashSet<BANNER>();
            this.COMPANY1 = new HashSet<COMPANY>();
            this.CONTENT_ATTACHMENT = new HashSet<CONTENT_ATTACHMENT>();
            this.CONTENTs = new HashSet<CONTENT>();
            this.CUSTOMER_SETTING = new HashSet<CUSTOMER_SETTING>();
            this.EVENTs = new HashSet<EVENT>();
            this.EVENT_TYPE = new HashSet<EVENT_TYPE>();
            this.GALLARY_TYPE = new HashSet<GALLARY_TYPE>();
            this.MENU_CATEGORY = new HashSet<MENU_CATEGORY>();
            this.NEWS_TYPE = new HashSet<NEWS_TYPE>();
            this.RECRUITMENTs = new HashSet<RECRUITMENT>();
            this.ROLEs = new HashSet<ROLE>();
            this.ROLE_MENU = new HashSet<ROLE_MENU>();
            this.SMS_TRACKING = new HashSet<SMS_TRACKING>();
            this.TENUREs = new HashSet<TENURE>();
            this.USERs = new HashSet<USER>();
            this.WIDGET_BUTTON = new HashSet<WIDGET_BUTTON>();
            this.WIDGETs = new HashSet<WIDGET>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string ContactNumber { get; set; }
        public string CompanyAddress { get; set; }
        public int CityId { get; set; }
        public string GSTN { get; set; }
        public string CTSNumber { get; set; }
        public string PAN { get; set; }
        public string LogoImage { get; set; }
        public string CallCentreNumber { get; set; }
        public string ComplaintNumber { get; set; }
        public string ContactPerson { get; set; }
        public string EmailId { get; set; }
        public string WebSite { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ACADEMIC_LEVEL> ACADEMIC_LEVEL { get; set; }
        public virtual ICollection<BANNER> BANNERs { get; set; }
        public virtual CITY CITY { get; set; }
        public virtual ICollection<COMPANY> COMPANY1 { get; set; }
        public virtual COMPANY COMPANY2 { get; set; }
        public virtual ICollection<CONTENT_ATTACHMENT> CONTENT_ATTACHMENT { get; set; }
        public virtual ICollection<CONTENT> CONTENTs { get; set; }
        public virtual ICollection<CUSTOMER_SETTING> CUSTOMER_SETTING { get; set; }
        public virtual ICollection<EVENT> EVENTs { get; set; }
        public virtual ICollection<EVENT_TYPE> EVENT_TYPE { get; set; }
        public virtual ICollection<GALLARY_TYPE> GALLARY_TYPE { get; set; }
        public virtual ICollection<MENU_CATEGORY> MENU_CATEGORY { get; set; }
        public virtual ICollection<NEWS_TYPE> NEWS_TYPE { get; set; }
        public virtual ICollection<RECRUITMENT> RECRUITMENTs { get; set; }
        public virtual ICollection<ROLE> ROLEs { get; set; }
        public virtual ICollection<ROLE_MENU> ROLE_MENU { get; set; }
        public virtual ICollection<SMS_TRACKING> SMS_TRACKING { get; set; }
        public virtual ICollection<TENURE> TENUREs { get; set; }
        public virtual ICollection<USER> USERs { get; set; }
        public virtual ICollection<WIDGET_BUTTON> WIDGET_BUTTON { get; set; }
        public virtual ICollection<WIDGET> WIDGETs { get; set; }
    }
}
