//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENT
    {
        public CONTENT()
        {
            this.CONTENT_ATTACHMENT = new HashSet<CONTENT_ATTACHMENT>();
        }
    
        public int ContentId { get; set; }
        public string ContentHeading { get; set; }
        public string Help { get; set; }
        public int MenuCategoryId { get; set; }
        public string ContentDescription { get; set; }
        public string VideoUrl { get; set; }
        public string MetaTag { get; set; }
        public string MetaKeyword { get; set; }
        public string UploadImage { get; set; }
        public string SlugUrl { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual ICollection<CONTENT_ATTACHMENT> CONTENT_ATTACHMENT { get; set; }
        public virtual MENU_CATEGORY MENU_CATEGORY { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
