//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_SETTING
    {
        public int CustomerSettingId { get; set; }
        public string SettingCategory { get; set; }
        public int SettingName { get; set; }
        public System.DateTime SettingValue { get; set; }
        public int CompanyId { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
    }
}
