//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_TYPE
    {
        public EVENT_TYPE()
        {
            this.EVENTs = new HashSet<EVENT>();
        }
    
        public int EventTypeId { get; set; }
        public string EventTypeName { get; set; }
        public int CompanyId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual ICollection<EVENT> EVENTs { get; set; }
    }
}
