//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        public int EventId { get; set; }
        public string EventHeading { get; set; }
        public int EventTypeId { get; set; }
        public string Help { get; set; }
        public int MenuCategoryId { get; set; }
        public System.DateTime EventDate { get; set; }
        public System.DateTime EventStartDate { get; set; }
        public System.DateTime EventEndDate { get; set; }
        public string EventDescription { get; set; }
        public string VideoUrl { get; set; }
        public string MetaTag { get; set; }
        public string MetaKeyword { get; set; }
        public string UploadImage { get; set; }
        public string SlugUrl { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual EVENT_TYPE EVENT_TYPE { get; set; }
        public virtual MENU_CATEGORY MENU_CATEGORY { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
