//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_CATEGORY
    {
        public MENU_CATEGORY()
        {
            this.CONTENTs = new HashSet<CONTENT>();
            this.EVENTs = new HashSet<EVENT>();
            this.MENU_CATEGORY1 = new HashSet<MENU_CATEGORY>();
        }
    
        public int MenuCategoryId { get; set; }
        public string MenuCategoryName { get; set; }
        public Nullable<int> PerentMenuCategoryId { get; set; }
        public Nullable<int> SequenceOrder { get; set; }
        public int CompanyId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual ICollection<CONTENT> CONTENTs { get; set; }
        public virtual ICollection<EVENT> EVENTs { get; set; }
        public virtual ICollection<MENU_CATEGORY> MENU_CATEGORY1 { get; set; }
        public virtual MENU_CATEGORY MENU_CATEGORY2 { get; set; }
    }
}
