//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public MENU()
        {
            this.MENU1 = new HashSet<MENU>();
            this.ROLE_MENU = new HashSet<ROLE_MENU>();
        }
    
        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> MenuParentId { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string Id { get; set; }
        public string Icon { get; set; }
        public Nullable<int> SequenceOrder { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<MENU> MENU1 { get; set; }
        public virtual MENU MENU2 { get; set; }
        public virtual ICollection<ROLE_MENU> ROLE_MENU { get; set; }
    }
}
