//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIN_CODE
    {
        public int PinCodeId { get; set; }
        public string PinCode { get; set; }
        public int City_d { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CITY CITY { get; set; }
    }
}
