//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        public ROLE()
        {
            this.ROLE_ACTION = new HashSet<ROLE_ACTION>();
            this.ROLE_MENU = new HashSet<ROLE_MENU>();
        }
    
        public int RoleId { get; set; }
        public long RoleBit { get; set; }
        public string RoleName { get; set; }
        public bool IsPublic { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual ICollection<ROLE_ACTION> ROLE_ACTION { get; set; }
        public virtual ICollection<ROLE_MENU> ROLE_MENU { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
