//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_MENU
    {
        public int RoleMenuId { get; set; }
        public int RoleId { get; set; }
        public int MenuId { get; set; }
        public int CompanyId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual MENU MENU { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
