//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_ACTION
    {
        public int RoleActionId { get; set; }
        public int RoleId { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ROLE ROLE { get; set; }
    }
}
