//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST_BO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.APP_ERROR_LOG = new HashSet<APP_ERROR_LOG>();
            this.BANNERs = new HashSet<BANNER>();
            this.BANNERs1 = new HashSet<BANNER>();
            this.CONTENTs = new HashSet<CONTENT>();
            this.CONTENTs1 = new HashSet<CONTENT>();
            this.CONTENT_ATTACHMENT = new HashSet<CONTENT_ATTACHMENT>();
            this.CONTENT_ATTACHMENT1 = new HashSet<CONTENT_ATTACHMENT>();
            this.EVENTs = new HashSet<EVENT>();
            this.EVENTs1 = new HashSet<EVENT>();
            this.RECRUITMENTs = new HashSet<RECRUITMENT>();
            this.RECRUITMENTs1 = new HashSet<RECRUITMENT>();
            this.ROLEs = new HashSet<ROLE>();
            this.ROLEs1 = new HashSet<ROLE>();
            this.WIDGET_BUTTON = new HashSet<WIDGET_BUTTON>();
            this.WIDGET_BUTTON1 = new HashSet<WIDGET_BUTTON>();
            this.WIDGETs = new HashSet<WIDGET>();
            this.WIDGETs1 = new HashSet<WIDGET>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmployeeCode { get; set; }
        public string LoginId { get; set; }
        public byte[] Password { get; set; }
        public string EmailId { get; set; }
        public string Mobile { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityId { get; set; }
        public int CompanyId { get; set; }
        public int RoleBit { get; set; }
        public string UserPhoto { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> PasswordFailedAttempt { get; set; }
        public bool IsAccountLocked { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<APP_ERROR_LOG> APP_ERROR_LOG { get; set; }
        public virtual ICollection<BANNER> BANNERs { get; set; }
        public virtual ICollection<BANNER> BANNERs1 { get; set; }
        public virtual CITY CITY { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        public virtual ICollection<CONTENT> CONTENTs { get; set; }
        public virtual ICollection<CONTENT> CONTENTs1 { get; set; }
        public virtual ICollection<CONTENT_ATTACHMENT> CONTENT_ATTACHMENT { get; set; }
        public virtual ICollection<CONTENT_ATTACHMENT> CONTENT_ATTACHMENT1 { get; set; }
        public virtual ICollection<EVENT> EVENTs { get; set; }
        public virtual ICollection<EVENT> EVENTs1 { get; set; }
        public virtual ICollection<RECRUITMENT> RECRUITMENTs { get; set; }
        public virtual ICollection<RECRUITMENT> RECRUITMENTs1 { get; set; }
        public virtual ICollection<ROLE> ROLEs { get; set; }
        public virtual ICollection<ROLE> ROLEs1 { get; set; }
        public virtual ICollection<WIDGET_BUTTON> WIDGET_BUTTON { get; set; }
        public virtual ICollection<WIDGET_BUTTON> WIDGET_BUTTON1 { get; set; }
        public virtual ICollection<WIDGET> WIDGETs { get; set; }
        public virtual ICollection<WIDGET> WIDGETs1 { get; set; }
    }
}
